//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Registration.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RestoranEntities : DbContext
    {
        public RestoranEntities()
            : base("name=RestoranEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Avtorizaciya> Avtorizaciya { get; set; }
        public virtual DbSet<Bludo> Bludo { get; set; }
        public virtual DbSet<EdiniciIzmereniya> EdiniciIzmereniya { get; set; }
        public virtual DbSet<Menu> Menu { get; set; }
        public virtual DbSet<Polzovateli> Polzovateli { get; set; }
        public virtual DbSet<Prodazhi> Prodazhi { get; set; }
        public virtual DbSet<Prodykti> Prodykti { get; set; }
        public virtual DbSet<Roli> Roli { get; set; }
        public virtual DbSet<Sostav> Sostav { get; set; }
        public virtual DbSet<SpisokZakupok> SpisokZakupok { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TipBluda> TipBluda { get; set; }
    }
}
