//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PR3._2_Koshelevskaya.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sostav
    {
        public int ID { get; set; }
        public int IDBluda { get; set; }
        public int IDProdykta { get; set; }
        public int KolichestvoProdykta { get; set; }
        public int IDEdiniciIzmereniya { get; set; }
    
        public virtual Bludo Bludo { get; set; }
        public virtual EdiniciIzmereniya EdiniciIzmereniya { get; set; }
        public virtual Prodykti Prodykti { get; set; }
    }
}
